open-mmlab/mmgeneration

tools/evaluation.py
I have tested on `PGGAN` with `--sample-cfg transition_weight=xxx` and it works.
=> [Fix] fix loss of sample-cfg argument 

README.md, README_zh-CN.md
There is a typo in the README. This PR changes the word `Learing` to `Learning`.
=> Change 'Learing' to 'Learning' in README

configs/styleganv2/stylegan2_c2_apex_fp16_quicktest_ffhq_256_b4x8_800k.py, configs/styleganv2/stylegan2_c2_fp16-global_quicktest_ffhq_256_b4x8_800k.py, configs/styleganv2/stylegan2_c2_fp16_quicktest_ffhq_256_b4x8_800k.py, mmgen/apis/train.py, mmgen/core/runners/apex_amp_utils.py, mmgen/core/runners/checkpoint.py, mmgen/core/runners/dynamic_iterbased_runner.py, mmgen/core/runners/fp16_utils.py, mmgen/datasets/__init__.py, mmgen/datasets/quick_test_dataset.py, mmgen/models/architectures/stylegan/generator_discriminator_v2.py, mmgen/models/architectures/stylegan/modules/styleganv2_modules.py, mmgen/models/gans/base_gan.py, mmgen/models/gans/static_unconditional_gan.py, mmgen/models/losses/disc_auxiliary_loss.py, mmgen/models/losses/gen_auxiliary_loss.py, mmgen/ops/conv2d_gradfix.py, setup.cfg, tests/test_cores/test_fp16_utils.py, tests/test_datasets/test_quicktest_dataset.py, tests/test_modules/test_stylev2_archs.py, tools/dist_train.sh
Add support for mixed-precision training with `torch.cuda.amp` (PyTorch >= 1.6.0) and `apex.amp` (need to install [apex](https://github.com/NVIDIA/apex) mannually). Since `torch.cuda.amp` is only supported after `1.6.0`, we add the support for `apex.amp`, so that users can adopt mixed-precision training for previous PyTorch version.
* add fp16_utils to introduce `auto_fp16` function
* add the example for training stylegan2
=> [Feature] Support FP16 mixed-precision training

mmgen/core/hooks/__init__.py, mmgen/core/hooks/ceph_hooks.py
Currently, we only support uploading with `petrel` which is a private package similar to `Boto3`. In the future, we will support uploading with `Boto3`.
=> [Feature] Add support for uploading checkpoints to Ceph system (cloud server)

tools/evaluation.py
Use if-else to judge whether config is valid, and ignore configs whose `data_root` is `None`.
=> [Fix] Fix error when `data_root` option in val_cfg or test_cfg are set as None

apps/stylegan_projector.py, mmgen/datasets/samplers/distributed_sampler.py, mmgen/datasets/singan_dataset.py, mmgen/models/architectures/dcgan/generator_discriminator.py, mmgen/models/architectures/lsgan/generator_discriminator.py, mmgen/models/architectures/positional_encoding.py, mmgen/models/architectures/singan/generator_discriminator.py, mmgen/models/architectures/singan/positional_encoding.py, mmgen/models/architectures/stylegan/generator_discriminator_v1.py, mmgen/models/architectures/stylegan/generator_discriminator_v2.py, mmgen/models/architectures/stylegan/modules/styleganv2_modules.py, mmgen/models/architectures/stylegan/mspie.py, mmgen/models/losses/gen_auxiliary_loss.py, mmgen/models/misc.py, tests/test_models/test_pggan.py, tests/test_models/test_stylegan1.py
This PR changes the use of the package `math` to `numpy`. The detailed changes are as follows:
1. `math.log2(...)` -> `np.log2(...)`
2. `math.cos(...)` -> `np.cos(...)`
3. `math.pi` -> `np.pi`
4. `math.ceil(...)` -> `int(np.ceil(...))`
5. `math.log(...)` -> `np.log(...)`
6. `math.pow(...)` -> `np.power(...)`
7. `math.sqrt(...)` -> `np.sqrt(...)`
8. `math.floor(...)` -> `int(np.floor(...))`
9. `math.isclose(..., abs_tol=...)` -> `np.isclose(..., atol=...)`
=> Change math to numpy

mmgen/core/evaluation/eval_hooks.py, mmgen/core/evaluation/metrics.py
Two bugs in the original implementation:
1. `break` in eval hook
2. gather features only for `pytorch` style in FID
=> [Fix] Fix bug in eval hook and fid metric

mmgen/core/evaluation/eval_hooks.py
Allow users to pass a 'interval dict' which contains 'milestones' and 'interval'.
```python
evaluation = dict(
type='GenerativeEvalHook',
interval=dict(
milestones=[500000, 750000],
interval=[10000, 4000, 2000])
...
)
```
=> [Feature] support dynamic eval interval in eval hook

mmgen/models/architectures/dcgan/generator_discriminator.py
Since `conv_cfg` cannot make any difference easily, we just remove this argument for clear and simple usage.
=> [Enhancement] Remove conv_cfg argument in dcgan

configs/_base_/models/biggan-deep_128x128_cvt_hugging-face_rgb.py, configs/_base_/models/biggan-deep_256x256_cvt_hugging-face_rgb.py, configs/_base_/models/biggan-deep_512x512_cvt_hugging-face_rgb.py, configs/_base_/models/biggan_128x128.py, configs/_base_/models/biggan_128x128_cvt_BigGAN-PyTorch_rgb.py, configs/biggan/README.md, configs/biggan/biggan_imagenet1k_128x128_b32x8_1500k.py
1. Provide benchmark with evaluation results and converted weights of BigGAN.
2. Provide corresponding configs for users.
Since training on ImageNet and [conditional model interpolation](https://github.com/open-mmlab/mmgeneration/pull/78) are still ongoing. This benchmark needs further improvement in the future.
=> [Feature] Release a benchmark for BigGAN/BigGAN-Deep

mmgen/datasets/builder.py
In some servers, the original implementation causes an unacceptable stop in training. Thus, we relax the constraint in resources to avoid being killed by the system.
=> [Fix] Add soft limit to the maximum number of open file descriptors

mmgen/core/evaluation/__init__.py, mmgen/core/evaluation/evaluation.py, mmgen/core/evaluation/metrics.py, mmgen/models/losses/__init__.py, mmgen/models/losses/pixelwise_loss.py, mmgen/models/losses/utils.py, tests/test_cores/test_metrics.py
Different from gan metrics, probabilistic metrics:
1. calculated with reconstruction tasks, and can 
2. calculated by a group of parameters but not fake and real images
Therefore, we design a list called `probabilistic_metric_name` to contain probabilistic metrics in `single_gpu_online_evaluation` . When evaluation with those metric separately.
When evaluating those probabilistic metrics, we use set forward mode as **reconstruction**.
We default that all **probabilistic model**  all support this mode. Unlike `forward_test`  which starts with random noise, `mode=reconstruction` performs a reconstruction behavior with given data and returns a dict containing desired probabilistic parameters.
We also slightly modify the batch truncation operation to make the `Metric.feed` support dict input. …
=> [Feature] Support KLD metric and support evaluation for probabilistic models

configs/biggan/README.md, configs/pggan/README.md, configs/sagan/README.md, configs/sngan_proj/README.md, configs/styleganv1/README.md, configs/styleganv2/README.md
Add blank line before `"```"`  symbol.
=> [Fix] Fix latex rendering in README files.

mmgen/core/evaluation/eval_hooks.py, mmgen/core/evaluation/metrics.py, tools/utils/translation_eval.py
=> [Fix] Fix bug of real samples number calculation in DDP evaluation

.github/workflows/build.yml, .pre-commit-config.yaml
Update `.pre-commit-config.yaml` and `build.yml` to support markdown lint check.
=> [Feature] Add the official markdownlint hook

mmgen/datasets/pipelines/augmentation.py, tests/test_datasets/test_pipelines/test_augmentation.py
Totally fix two bugs:
1. Error when `-1` in `scale`.
2. `self.scale` and `self.size_factor` can be changed in each sample's resize process and may influence the resize behavior for the following samples.
=> [Fix] Fix bug of 'resize' when -1 in 'scale'

configs/positional_encoding_in_gans/singan_csg_bohemian.py, configs/positional_encoding_in_gans/singan_csg_fish.py, configs/positional_encoding_in_gans/singan_interp-pad_balloons.py, configs/positional_encoding_in_gans/singan_interp-pad_disc-nobn_balloons.py, configs/positional_encoding_in_gans/singan_interp-pad_disc-nobn_fish.py, configs/positional_encoding_in_gans/singan_spe-dim4_bohemian.py, configs/positional_encoding_in_gans/singan_spe-dim4_fish.py, configs/positional_encoding_in_gans/singan_spe-dim8_bohemian.py, configs/singan/singan_fish.py, mmgen/datasets/singan_dataset.py
math.log(a, b) is equal to np.log(a)/np.log(b)
=> [Fix] singan errors

mmgen/models/architectures/sngan_proj/generator_discriminator.py, mmgen/models/architectures/sngan_proj/modules.py, tests/test_modules/test_sngan_proj_archs.py
In #159, we support `Ajbrock`'s spectral norm, and the default style of spectral norm is changed.
Therefore we support users to select the style of spectral norm and set the default style to `torch`.
=> [Fix] Add `sn_style` option for SAGAN and SNGAN.

docs/en/quick_run.md
Fix invalid links for pix2pix weights by removing `versionID`.
=> [Fix] Fix invalid links for pix2pix weights

apps/styleclip.py, mmgen/models/architectures/__init__.py, mmgen/models/architectures/arcface/__init__.py, mmgen/models/architectures/arcface/helpers.py, mmgen/models/architectures/arcface/id_loss.py, mmgen/models/architectures/arcface/model_irse.py, mmgen/models/losses/__init__.py, mmgen/models/losses/gen_auxiliary_loss.py, requirements/runtime.txt, setup.cfg, tests/test_modules/test_arcface.py
Support `StyleClip` application.
=> [Feature] Support styleclip

docs/en/quick_run.md, mmgen/apis/train.py
We support CPU training. Reference: https://github.com/open-mmlab/mmdetection/pull/7016
=> [Feature] Support CPU training 

.github/workflows/build.yml, docs/en/get_started.md
mmcv-full is only compiled on PyTorch 1.x.0 because the compatibility usually holds between 1.x.0 and 1.x.1. If your PyTorch version is 1.x.1, you can install mmcv-full compiled with PyTorch 1.x.0 and it usually works well.
Related PR: https://github.com/open-mmlab/mmtracking/pull/409
=> [Enhancement] Update the installation of MMCV

.pre-commit-config.yaml, setup.cfg
1. Remove `seed-isort-config` in `=pre-commit hook
2. Upgrade `isort` to v5.10.1 (latest version)
3. Replace `known_standard_library` with `extra_standard_library`
Related PR: https://github.com/open-mmlab/mmflow/pull/87
=> [Enhancement] Upgrade isort in pre-commit hook

demo/conditional_demo.py, demo/ddpm_demo.py, demo/unconditional_demo.py, docs/en/get_started.md, docs/en/quick_run.md, mmgen/apis/__init__.py, mmgen/apis/inference.py, mmgen/datasets/grow_scale_image_dataset.py, mmgen/datasets/unconditional_image_dataset.py, tests/test_apis/test_inference.py
PR #227 is not completed, So I send a new PR for that.
=> Fix the typo uncoditional -> unconditional

tools/train.py
The validation pipeline should be loaded from `cfg.data.val`, but it is currently loading from  `cfg.data.train`
=> Fix issue #242

tools/evaluation.py, tools/train.py
Refers to https://github.com/open-mmlab/mmdetection/pull/7019
=> [Fix] Fix bug in non-distributed training/testing

mmgen/core/hooks/ema_hook.py, tests/test_cores/test_ema_hooks.py
This PR modify ema hook, refer to https://github.com/NVlabs/stylegan3.
1. Support update momentum in `EMA` Hook.
2. Add related unittest.
=> [Feature] Support dynamic EMA

mmgen/models/diffusions/sampler.py
The return type of `numpy.random.choice` is different under Windows and Linux.
Add a force type convention after sampling.
=> [Fix] fix ddpm sampler under win10

docs/en/quick_run.md, tools/dist_eval.sh, tools/dist_train.sh
Ref: https://github.com/open-mmlab/mmselfsup/pull/232
=> [Feature] Add multi machine dist_train

apps/modified_sefa.py, apps/styleclip.py
Refer to https://github.com/open-mmlab/mmediting/pull/808.
=> [Fix] use hyphen for command line args in apps

.pre-commit-config.yaml, mmgen/models/architectures/stylegan/generator_discriminator_v3.py, mmgen/models/gans/static_unconditional_gan.py, tests/test_models/test_static_unconditional_gan.py
In StyleGANv3, we need to set `force_fp32` to False during training and set `updates_ema` to True during disc training.
I tackle this by adding an extra function to pass kwargs in s3 generator.
=> [Feature] support pass s3 training kwargs

configs/styleganv3/metafile.yml, configs/styleganv3/stylegan3_r_ada_fp16_gamma3.3_metfaces_1024_b4x8.py, configs/styleganv3/stylegan3_t_ada_fp16_gamma6.6_metfaces_1024_b4x8.py, configs/styleganv3/stylegan3_t_noaug_fp16_gamma32.8_ffhq_1024_b4x8.py, mmgen/core/evaluation/metrics.py, mmgen/models/architectures/stylegan/ada/augment.py, mmgen/models/architectures/stylegan/ada/grid_sample_gradfix.py, mmgen/models/architectures/stylegan/ada/misc.py, mmgen/models/architectures/stylegan/ada/upfirdn2d.py, mmgen/models/architectures/stylegan/generator_discriminator_v2.py, mmgen/models/architectures/stylegan/modules/styleganv3_modules.py, mmgen/models/gans/static_unconditional_gan.py, tests/test_models/test_static_unconditional_gan.py, tests/test_modules/test_stylev2_archs.py, tests/test_modules/test_stylev3_archs.py
1. Support `ada` augment.
2. Support `ADAStyleGAN2Discriminator` and its training.
=> [Feature] support ada module and training

mmgen/apis/train.py, tools/evaluation.py
Refers to https://github.com/open-mmlab/mmclassification/pull/752
```
data = dict(
samples_per_gpu=64,
workers_per_gpu=4,
train=dict(type='xxx', ...),
val=dict(type='xxx', ...),
test=dict(type='xxx', ...),
val_dataloader=dict(samples_per_gpu=8, workers_per_gpu=2),
test_dataloader=dict(samples_per_gpu=8, workers_per_gpu=2),
)
```
=> [Enhance] Support train_dataloader, val_dataloader and test_dataloader settings

mmgen/core/evaluation/metric_utils.py, mmgen/core/evaluation/metrics.py
Since compute_metrics is only performed on main process, we directly set `rank`=0 and `num_gpus`=1 in compute_pr_metric function.
=> [Fix] Fix PrecisionAndRecall metric

configs/pix2pix/pix2pix_vanilla_unet_bn_aerial2maps_b1x1_220k.py, configs/pix2pix/pix2pix_vanilla_unet_bn_facades_b1x1_80k.py, configs/pix2pix/pix2pix_vanilla_unet_bn_maps2aerial_b1x1_220k.py, configs/pix2pix/pix2pix_vanilla_unet_bn_wo_jitter_flip_edges2shoes_b1x4_190k.py, requirements/runtime.txt
1. Set mmcls>=1.0.0rc0
2. Remove sample_idx and other unneed meta keys in `test_dataloader` of pix2pix.
=> [Fix] Limit mmcls version and remove unneeded meta keys in test_dataloader of pix2pix

tools/train.py
Enhance `tools/train.py`. `AmpOptimizer` will be substituted for original optimizer. To start up amp training, just add `--amp` after training command.
=> support amp training

configs/lsgan/lsgan_dcgan-archi_lr-1e-4_lsun-bedroom_64_b128x1_12m.py, configs/lsgan/lsgan_lsgan-archi_lr-1e-4_lsun-bedroom_128_b64x1_10m.py, configs/styleganv3/stylegan3_t_noaug_fp16_gamma32.8_ffhq_1024_b4x8.py
1. Error: type='StaticUnconditionalGAN'.
2. Only use 50k real images for evaluation, not total set.
=> Fix type error in stylegan3 config and metrics in lsgan config

.pre-commit-config.yaml, mmgen/models/architectures/ddpm/modules.py
MMCV v 1.6.2 support`SiLU` activation function and registers it to `ACTIVATION_LAYERS`.  This conflict with MMGen's `SiLU` implementation.
Only register `SiLU` when MMCV version is lower than 1.6.2
If this PR introduces a new feature, it is better to list some use cases here, …
=> [Fix] fix SiLU activation

mmgen/models/architectures/ddpm/denoising.py
Simply fix typos in docstring.
=> fix typos in docstring

mmgen/models/losses/__init__.py, mmgen/models/losses/gen_auxiliary_loss.py, tests/test_losses/test_gen_auxiliary_loss.py
Perceptual Loss is an important and commonly used loss for improving perceptual quality in generation tasks. As discussed in [issues 445](https://github.com/open-mmlab/mmgeneration/issues/445), it is necessary to support perceptual loss in style transfer.
This PR makes modifications to files `mmgeneration/mmgen/models/losses/__init__.py` and `mmgeneration/mmgen/models/losses/gen_auxiliary_loss.py`. And there are unit tests in `mmgeneration/tests/test_losses/test_gen_auxiliary_loss.py` as well.
=> [Feature] Support Perceptual Loss

mmgen/models/architectures/ddpm/denoising.py, mmgen/models/diffusions/utils.py
`var_indexed = torch.from_numpy(var)[index].float()` this line will result in an error with `torch==1.13.0+cu117`.
because the tensor `torch.from_numpy(var)` and index `index` may not on the same device.
Change to `var_indexed = torch.from_numpy(var)[index.cpu()].float()` resolves the issue.
Screenshots after executing `python tools/train.py configs/improved_ddpm/ddpm_cosine_hybird_timestep-4k_drop0.3_cifar10_32x32_b8x16_500k.py`.
=> fix tensor and index aren't on the same device error

docs/en/tutorials/customize_models.md
Fix typo in documentation 
I've added a closing ' to the documentation
**Before PR**:
- [x ] I have read and followed the workflow indicated in the [CONTRIBUTING.md](https://github.com/open-mmlab/mmediting/blob/master/.github/CONTRIBUTING.md) to create this PR.
- [ x] Pre-commit or linting tools indicated in [CONTRIBUTING.md](https://github.com/open-mmlab/mmediting/blob/master/.github/CONTRIBUTING.md) are used to fix the potential lint issues.
- [ x] Bug fixes are covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ x] New functionalities are covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ x] The documentation has been modified accordingly, including docstring or example tutorials.
**After PR**:
=> Add missing ' in documentation

.github/workflows/merge_stage_test.yml, README.md, README_zh-CN.md, docs/en/changelog.md, mmgen/version.py
=> Bump version to v0.7.3
