open-mmlab/mmgeneration

mmgen/core/evaluation/eval_hooks.py
mmgen/core/evaluation/metrics.py

This PR is to improve the implementation of FID and eval hook. The original implementation will cause redundant RAM cost, which may cause the weird stop by the system call without any error information.

[Fix] Improve the FID and eval hook

---

README_zh-CN.md

Add `mmgeneration` introduction in `Projects in OpenMMLab`.

[Enhancement] add a line for mmgen 

---

tools/misc/print_config.py
tools/train.py

I think `--options` is unnecessary for newly released projects.

Clean deprecated argument

---

mmgen/models/architectures/__init__.py
mmgen/models/architectures/lsgan/__init__.py
mmgen/models/architectures/lsgan/generator_discriminator.py
tests/test_modules/test_lsgan_archs.py
tools/evaluation.py

Add support for LSGAN experiments
Add architectures for LSGAN Generator and Discriminator.

[Feature] Add LSGAN architecture

---

mmgen/models/architectures/stylegan/generator_discriminator_v2.py

Fix the docstring of `StyleGAN2Discriminator`.

Change docstring of StyleGAN2Discriminator

---

mmgen/core/evaluation/eval_hooks.py
mmgen/core/evaluation/metrics.py

1. Modify the original IS metric to support distributed inference.
2. Add IS metric in `GenerativeEvalHook`
3. Support multiple metrics in saving the best checkpoint respectively.

[Enhancement] Distributed IS metric, add IS in Generative EvalHook, and support mulitiple metrics in saving best checkpoints

---

configs/cyclegan/cyclegan_lsgan_id0_resnet_in_1x1_250k_summer2winter.py
configs/cyclegan/cyclegan_lsgan_id0_resnet_in_1x1_250k_winter2summer.py
configs/cyclegan/cyclegan_lsgan_id0_resnet_in_1x1_270k_horse2zebra.py
configs/cyclegan/cyclegan_lsgan_id0_resnet_in_1x1_270k_zebra2horse.py
configs/cyclegan/cyclegan_lsgan_id0_resnet_in_1x1_80k_facades.py
configs/cyclegan/cyclegan_lsgan_resnet_in_1x1_250k_summer2winter.py
configs/cyclegan/cyclegan_lsgan_resnet_in_1x1_250k_winter2summer.py
configs/cyclegan/cyclegan_lsgan_resnet_in_1x1_270k_horse2zebra.py
configs/cyclegan/cyclegan_lsgan_resnet_in_1x1_270k_zebra2horse.py
configs/cyclegan/cyclegan_lsgan_resnet_in_1x1_80k_facades.py
configs/pix2pix/pix2pix_vanilla_unet_bn_1x1_80k_facades.py
configs/pix2pix/pix2pix_vanilla_unet_bn_a2b_1x1_220k_maps.py
configs/pix2pix/pix2pix_vanilla_unet_bn_b2a_1x1_220k_maps.py
configs/pix2pix/pix2pix_vanilla_unet_bn_wo_jitter_flip_1x4_190k_edges2shoes.py
configs/singan/singan_balloons.py
configs/singan/singan_bohemian.py
configs/singan/singan_fish.py
mmgen/core/ddp_wrapper.py
mmgen/core/hooks/visualization.py

This is a temporal solution to solve the conflicts (#32) with other repos in OpenMMLab.

[Fix] Fix conflicts with other repos in OpenMMLab

---

mmgen/core/evaluation/evaluation.py
mmgen/core/evaluation/metrics.py

1. fix the bug in online evaluation with condition dataset 
2. improve data feeding operation
3. simplify torch version check in `load_inception`

[Fix] Fix bug in evaluation 

---

mmgen/models/architectures/biggan/__init__.py
mmgen/models/architectures/biggan/generator_discriminator.py
tests/test_modules/test_biggan_archs.py

1. Add more unit-test for `BIGGAN`.
2. Fix a bug in output dict.

[Enhancement] Add more unit test for BIGGAN

---

mmgen/core/hooks/ema_hook.py
mmgen/models/gans/basic_conditional_gan.py

1. Fix data copy bug in EMA Hook.
2. Fix generator's step bug in `BasiccGAN`.

[Fix] Fix bugs in EMA Hook and BasicConditionalGAN

---

configs/_base_/datasets/cifar10_noaug.py
configs/_base_/datasets/cifar10_random_noise.py
configs/_base_/datasets/imagenet_128.py
configs/_base_/datasets/imagenet_256.py
configs/_base_/datasets/imagenet_noaug_128.py
configs/_base_/datasets/imagenet_noaug_256.py
configs/_base_/datasets/imagenet_rgb.py
mmgen/datasets/pipelines/__init__.py
mmgen/datasets/pipelines/augmentation.py
setup.cfg
tests/test_datasets/test_pipelines/test_augmentation.py
tools/utils/inception_stat.py

1. support ImageNet 128 and ImageNet 256
2. add more  CIFAR10 datasets
3. add more augmentation methods

[Enhancement] Add more conditional datasets + and data augmentation

---

demo/conditional_demo.py
mmgen/apis/__init__.py
mmgen/apis/inference.py
tests/test_models/test_basic_conditional_gan.py

1. Support sample for conditional GAN
2. Add unit test for BasiccGAN

[Feature] Support sample for conditional GAN

---

configs/_base_/models/sngan_proj_32x32.py
configs/sngan_proj/README.md
configs/sngan_proj/sngan_proj_cifar10_32_lr-2e-4_b64x1_wReLUinplace.py
configs/sngan_proj/sngan_proj_cifar10_32_lr-2e-4_b64x1_woReLUinplace.py
tools/utils/inception_stat.py

1. add config for SNGAN-CIFAR10
2. support use all images in subset to extract inception stat

[Feature] Release training config for SNGAN on CIFAR10

---

apps/conditional_interpolate.py
apps/interpolate_sample.py
configs/biggan/README.md
docs/tutorials/applications.md
mmgen/models/architectures/__init__.py
mmgen/models/architectures/biggan/generator_discriminator.py
mmgen/models/architectures/biggan/generator_discriminator_deep.py

1. Modify BigGAN and BigGAN-Deep's forward function to support truncation, interpolation, and pre-trained weights with output channels order `RGB`.
2. Support interpolation for Conditional Models.

[Enhancement] Support interpolation for Conditional Models + Modify BigGAN's forward function 

---

mmgen/utils/collect_env.py

[FIX] Fix CUDA_HOME ImportError with mmcv >= 1.3.11

---

tools/evaluation.py

Fix issue[117](https://github.com/open-mmlab/mmgeneration/issues/117#issue-996705918).

[Fix] Fix an argument in tools/evaluation.py

---

README.md
README_zh-CN.md

Add related-applications link in `README`.

[Doc] Add related-applications link in README

---

docs/conf.py

Follow  https://github.com/open-mmlab/mmocr/pull/655
Since Chinese docs are not ready for the new theme, it is not modified at this moment. Further modification / PR is required.

[docs] update docs/conf.py to use shared items

---

.github/workflows/build.yml
.github/workflows/deploy.yml

Cancel previous runs that are not completed

[CI] Cancel previous runs that are not completed 

---

README_zh-CN.md

Fix typos in `README_zh-CN.md`.

[docs] Fix typos in README_zh-CN 

---

tests/test_losses/test_pixelwise_loss.py
tests/test_modules/test_stylev1_archs.py
tests/test_modules/test_stylev2_archs.py

Fix unit test of pixelwise loss as well.

[Fix] Add unit test of `mix_prob = 1` for stylegan1 and stylegan2

---

README.md

Fix a README link mentioned in #225 .

[Fix] Fix issue#225

---

README.md

Add some html sentences on README.md  to show OpenMMLab website and platform link.

add OpenMMLab website and platform links

---

.dev_scripts/github/update_model_index.py
configs/biggan/README.md
configs/cyclegan/README.md
configs/cyclegan/metafile.yml
configs/dcgan/README.md
configs/dcgan/metafile.yml
configs/ggan/README.md
configs/improved_ddpm/README.md
configs/improved_ddpm/metafile.yml
configs/lsgan/README.md
configs/pggan/README.md
configs/pix2pix/README.md
configs/positional_encoding_in_gans/README.md
configs/sagan/README.md
configs/singan/README.md
configs/singan/metafile.yml
configs/sngan_proj/README.md
configs/styleganv1/README.md
configs/styleganv2/README.md
configs/wgan-gp/README.md

Refers to: https://gist.github.com/zhouzaida/e3ccf34400d468ce7e8edb9ac3c499e8

[Improve] Revise structure of Readme files

---

.github/workflows/build.yml

- Add win-ci in .github/workflows/build.yml
ref pr: https://github.com/open-mmlab/mmediting/pull/732

[Enhancement] Add win-ci

---

README.md
README_zh-CN.md

Ref: https://github.com/open-mmlab/mmcv/pull/1744/files

[Enhancement] add mmrotate and adjust project introduction

---

configs/styleganv3/stylegan3_r_afhqv2_512_b4x8_official.py
configs/styleganv3/stylegan3_r_ffhqu_256_b4x8_official.py
configs/styleganv3/stylegan3_t_afhqv2_512_b4x8_official.py
configs/styleganv3/stylegan3_t_ffhqu_256_b4x8_official.py
mmgen/models/architectures/stylegan/generator_discriminator_v3.py
tests/test_modules/test_stylev3_archs.py

Modify the s3 generator.
1. Remove train function.
2. Support feed latent.

[Fix] Update s3 generator

---

mmgen/datasets/builder.py
tools/train.py
work_dirs

Refer to https://github.com/open-mmlab/mmselfsup/pull/228

[Feature] Add diff seeds to diff ranks and set torch seed in worker_init_fn 

---

.github/workflows/build.yml
tests/test_cores/test_metrics.py

Reduce the number of workers in the unit test.

[Fix] Fix OOM in Win CI

---

mmgen/datasets/builder.py
mmgen/datasets/samplers/distributed_sampler.py
mmgen/utils/__init__.py
mmgen/utils/dist_util.py

Refers to https://github.com/open-mmlab/mmdetection/pull/7440/files and https://github.com/open-mmlab/mmediting/pull/815.

[Enchance] Support random seed for distributed sampler

---

README.md
README_zh-CN.md

Refers to https://github.com/open-mmlab/mmediting/pull/800/

[Docs] Add brief installation steps in README(_zh-CN).md

---

.pre-commit-config.yaml
configs/_base_/datasets/unconditional_imgs_flip_lanczos_resize_256x256.py
configs/styleganv3/README.md
configs/styleganv3/metafile.yml
configs/styleganv3/stylegan3_t_noaug_fp16_gamma2.0_ffhq_256_b4x8.py
configs/styleganv3/stylegan3_t_noaug_fp16_gamma32.8_ffhq_1024_b4x8.py

1. Update S3 training configs.
2. Update S3 README with training results.

[Feature] update s3 with training results

---

README.md
README_zh-CN.md
docs/en/changelog.md
mmgen/version.py

Bump version to 0.7.0

---

mmgen/models/architectures/stylegan/generator_discriminator_v2.py

Fix a bug if ada_aug is set to None in ADAStyleGANv2Discriminator.

Fix ada typo

---

README.md
README_zh-CN.md
docs/en/changelog.md
mmgen/version.py

Bump version to 0.7.1

---

.github/workflows/build.yml
requirements/runtime.txt

Remove PyTorch container and `APT` commands, and install all dependencies via `pip`.

[Fix] Fix workflow

---

docs/en/faq.md
docs/en/get_started.md

Refers to https://github.com/open-mmlab/mmdetection/pull/7897.

[Doc] rewrite the installation guide

---

README.md
README_zh-CN.md
dummy.py

As title. Ref: https://github.com/open-mmlab/mmediting/pull/898.

[Doc] Format README and README_zh

---

.github/workflows/build.yml
tests/test_modules/test_mspie_archs.py
tests/test_modules/test_stylev1_archs.py
tests/test_modules/test_stylev2_archs.py

This PR may solve the randomness of StyleGAN1 and StyleGAN2's unit test coverage.
Then the #318, #319, #317  can be merged safely.

[Unit Test] Enchance coverage for StyleGAN 1 and StyleGAN2

---

requirements/docs.txt

Refers to https://github.com/open-mmlab/mmaction2/pull/1670

[Install] Update requirements about opencv-python

---

configs/_base_/models/improved_ddpm/ddpm_32x32.py
configs/_base_/models/stylegan/stylegan2_base.py
configs/pix2pix/pix2pix_vanilla_unet_bn_facades_b1x1_80k.py
demo/ddpm_demo.py
docs/en/faq.md
docs/en/get_started.md
mmgen/apis/inference.py
mmgen/models/diffusions/base_diffusion.py

1. update get_started.md and faq.md
2. update scripts in demo

[Refactor] dev-1.x Update get_started and demo

---

.dev_scripts/benchmark_regression/train_benchmark.py

[Enhance] support train benchmark resume from latest checkpoint

---

.dev_scripts/benchmark_regression/test_benchmark.py
configs/_base_/datasets/cifar10_noaug.py
configs/_base_/datasets/cifar10_nopad.py
configs/_base_/datasets/imagenet_128.py
configs/_base_/datasets/imagenet_noaug_128.py
configs/_base_/datasets/imagenet_noaug_64.py
mmgen/datasets/unconditional_image_dataset.py
mmgen/models/architectures/biggan/generator_discriminator.py
mmgen/models/architectures/biggan/generator_discriminator_deep.py
mmgen/models/architectures/biggan/modules.py
mmgen/models/architectures/dcgan/generator_discriminator.py
mmgen/models/architectures/ddpm/denoising.py
mmgen/models/architectures/ddpm/modules.py
mmgen/models/architectures/lsgan/generator_discriminator.py
mmgen/models/architectures/pggan/generator_discriminator.py
mmgen/models/architectures/pggan/modules.py
mmgen/models/architectures/pix2pix/modules.py
mmgen/models/architectures/singan/modules.py
mmgen/models/architectures/sngan_proj/generator_discriminator.py
mmgen/models/architectures/sngan_proj/modules.py
mmgen/models/architectures/stylegan/modules/styleganv2_modules.py
mmgen/models/architectures/wgan_gp/generator_discriminator.py
mmgen/models/architectures/wgan_gp/modules.py
mmgen/visualization/vis_backend.py
tests/test_models/test_architectures/test_pggan/test_pggan_modules.py

Tests should pass after MMCV merging https://github.com/open-mmlab/mmcv/pull/2172 and MMCls fixing their dependency

[Refactor] Remove dependency on MMCV registry 

---

docs/zh_cn/tutorials/applications.md

Fix typo in zh_CN applications.md

[Docs] Fix typo in zh_CN applications.md

---

tests/test_losses/test_gen_auxiliary_loss.py
tests/test_ops/test_conv_gradfix.py

[Test] Skip unit tests that need tf32

---

.github/workflows/publish-to-pypi.yml
release

[Fix] Fix publish to pypi

---

.github/ISSUE_TEMPLATE/1-bug-report.yml
.github/ISSUE_TEMPLATE/2-feature-request.yml
.github/ISSUE_TEMPLATE/3-new-model.yml
.github/ISSUE_TEMPLATE/4-documentation.yml
.github/ISSUE_TEMPLATE/config.yml
.github/pull_request_template.md

To provide a user-friendly and efficient issue-creating experience, this PR improves existing issue templates by using issue forms.
Use issue forms in .github/ISSUE_TEMPLATE
If this PR introduces a new feature, it is better to list some use cases here, and update the …

[Enhancement] Improve issue template

---

.github/workflows/merge_stage_test.yml
.github/workflows/pr_stage_test.yml

[Fix] Revise 'pip' to 'python -m pip' in windows CI of `master` branch

---

.github/workflows/merge_stage_test.yml

[Fix] Install opencv for `merge_stage_test`

---

.github/workflows/merge_stage_test.yml
.github/workflows/pr_stage_test.yml
.pre-commit-config.yaml
requirements/runtime.txt
requirements/tests.txt

[Fix] deprecate codecov from requirements
